# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - picasoid-abdm-backend

on: push

env:
  USER_NAME: ${{vars.USER_NAME}}
  PASSWORD: ${{vars.PASSWORD}}
  SERVER_NAME: ${{vars.SERVER_NAME}}
  DATABASE_NAME: ${{vars.DATABASE_NAME}}
# Optional: environment variables can be injected here
# You can add these variables in your repository Settings - Secrets and variables - Actions - variables

# There are two jobs in this workflow - build and deploy
jobs:
  # Builds the application for production.
  # You should configure this environment as close as possible to the production environment, e.g. using Ubuntu for Linux apps, using the same Node version
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
