# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - picasoid-abdm-backend

# Run the workflow whenever change is pushed into the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  USER_NAME: ${{vars.USER_NAME}}
  PASSWORD: ${{vars.PASSWORD}}
  SERVER_NAME: ${{vars.SERVER_NAME}}
  DATABASE_NAME: ${{vars.DATABASE_NAME}}
# Optional: environment variables can be injected here
# You can add these variables in your repository Settings - Secrets and variables - Actions - variables

# There are two jobs in this workflow - build and deploy
jobs:
  # Builds the application for production.
  # You should configure this environment as close as possible to the production environment, e.g. using Ubuntu for Linux apps, using the same Node version
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run:
          npm install
          # Other scripts if configured should be added here, such as linting, formating

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: picasoid-abdm-backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
  # Deploy the application to Azure
